### ISSUE TITLE
Display Memos at Home screen

### ISSUE THREAD

**Issue by psmith586** [psmith586/QuarantineMemo#3]
use firebase/firestore package to fetch and display memos from collection('/memos') yo home screen.

Note: this is intended to be specific to uid of the logged in user but data already stored may or may not correctly correspond yet.

Once the data is correctly being pushed by CreateMemo component, we should be able to pull uid with the auth package: ex. auth().currentUser.uid then fetch data with that.

**Comment by robertIanClarkson** [comment]
Needs helper functions to display the number of locations and symptoms
